### ISSUE TITLE
Browser Desktop Display

### ISSUE THREAD

**Issue by lexus2727** [Lotus-Petal-Architecture/hunger-map#8]
![map pic 9](https://user-images.githubusercontent.com/48888775/102130237-9a15e800-3e1e-11eb-953c-9c4da6e8977c.png)

The banner's size is rendering too large on the browser. Also, the map's interface is hardly noticeable, making interaction difficult.

**Comment by erikYX** [comment]
You aren't seeing the updated stylesheet with the header style.. Do a hard refresh in your browser, or view in a Incognito Mode. 

Erik Amlee

Principal
_______________________________
Yes Exactly, Inc. | yesexactly.com | 413.325.8251
